<?

$optionsPaises = array(
  array('codigo'=>93, 'nome_pais'=>'Afeganistão'),
  array('codigo'=>27, 'nome_pais'=>'Africa do Sul'),
  array('codigo'=>355, 'nome_pais'=>'Albânia'),
  array('codigo'=>49, 'nome_pais'=>'Alemanha'),
  array('codigo'=>376, 'nome_pais'=>'Andorra'),
  array('codigo'=>244, 'nome_pais'=>'Angola'),
  array('codigo'=>1, 'nome_pais'=>'Anguilla'),
  array('codigo'=>1, 'nome_pais'=>'Antígua e Barbuda'),
  array('codigo'=>599, 'nome_pais'=>'Antilhas Holandesas'),
  array('codigo'=>966, 'nome_pais'=>'Arábia Saudita'),
  array('codigo'=>213, 'nome_pais'=>'Argélia'),
  array('codigo'=>54, 'nome_pais'=>'Argentina'),
  array('codigo'=>374, 'nome_pais'=>'Armênia'),
  array('codigo'=>297, 'nome_pais'=>'Aruba'),
  array('codigo'=>247, 'nome_pais'=>'Ascensão'),
  array('codigo'=>61, 'nome_pais'=>'Austrália'),
  array('codigo'=>43, 'nome_pais'=>'Áustria'),
  array('codigo'=>994, 'nome_pais'=>'Azerbaijão'),
  array('codigo'=>1, 'nome_pais'=>'Bahamas'),
  array('codigo'=>880, 'nome_pais'=>'Bangladesh'),
  array('codigo'=>1, 'nome_pais'=>'Barbados'),
  array('codigo'=>973, 'nome_pais'=>'Bahrein'),
  array('codigo'=>32, 'nome_pais'=>'Bélgica'),
  array('codigo'=>501, 'nome_pais'=>'Belize'),
  array('codigo'=>229, 'nome_pais'=>'Benim'),
  array('codigo'=>1, 'nome_pais'=>'Bermudas'),
  array('codigo'=>375, 'nome_pais'=>'Bielorrússia'),
  array('codigo'=>591, 'nome_pais'=>'Bolívia'),
  array('codigo'=>387, 'nome_pais'=>'Bósnia e Herzegovina'),
  array('codigo'=>267, 'nome_pais'=>'Botswana'),
  array('codigo'=>673, 'nome_pais'=>'Brunei'),
  array('codigo'=>359, 'nome_pais'=>'Bulgária'),
  array('codigo'=>226, 'nome_pais'=>'Burkina Faso'),
  array('codigo'=>257, 'nome_pais'=>'Burundi'),
  array('codigo'=>975, 'nome_pais'=>'Butão'),
  array('codigo'=>238, 'nome_pais'=>'Cabo Verde'),
  array('codigo'=>237, 'nome_pais'=>'Camarões'),
  array('codigo'=>855, 'nome_pais'=>'Camboja'),
  array('codigo'=>1, 'nome_pais'=>'Canadá'),
  array('codigo'=>7, 'nome_pais'=>'Cazaquistão'),
  array('codigo'=>237, 'nome_pais'=>'Chade'),
  array('codigo'=>56, 'nome_pais'=>'Chile'),
  array('codigo'=>86, 'nome_pais'=>'China'),
  array('codigo'=>357, 'nome_pais'=>'Chipre'),
  array('codigo'=>57, 'nome_pais'=>'Colômbia'),
  array('codigo'=>269, 'nome_pais'=>'Comores'),
  array('codigo'=>242, 'nome_pais'=>'Congo-Brazzaville<'),
  array('codigo'=>243, 'nome_pais'=>'Congo-Kinshasa'),
  array('codigo'=>850, 'nome_pais'=>'Coreia do Norte'),
  array('codigo'=>82, 'nome_pais'=>'Coreia do Sul'),
  array('codigo'=>225, 'nome_pais'=>'Costa do Marfim'),
  array('codigo'=>506, 'nome_pais'=>'Costa Rica'),
  array('codigo'=>385, 'nome_pais'=>'Croácia'),
  array('codigo'=>53, 'nome_pais'=>'Cuba'),
  array('codigo'=>45, 'nome_pais'=>'Dinamarca'),
  array('codigo'=>253, 'nome_pais'=>'Djibuti'),
  array('codigo'=>1, 'nome_pais'=>'Dominica'),
  array('codigo'=>20, 'nome_pais'=>'Egipto'),
  array('codigo'=>503, 'nome_pais'=>'El Salvador'),
  array('codigo'=>971, 'nome_pais'=>'Emirados Árabes Unidos'),
  array('codigo'=>593, 'nome_pais'=>'Equador'),
  array('codigo'=>291, 'nome_pais'=>'Eritreia'),
  array('codigo'=>421, 'nome_pais'=>'Eslováquia'),
  array('codigo'=>386, 'nome_pais'=>'Eslovénia'),
  array('codigo'=>34, 'nome_pais'=>'Espanha'),
  array('codigo'=>1, 'nome_pais'=>'Estados Unidos'),
  array('codigo'=>372, 'nome_pais'=>'Estónia'),
  array('codigo'=>251, 'nome_pais'=>'Etiópia'),
  array('codigo'=>679, 'nome_pais'=>'Fiji'),
  array('codigo'=>63, 'nome_pais'=>'Filipinas'),
  array('codigo'=>358, 'nome_pais'=>'Finlândia'),
  array('codigo'=>33, 'nome_pais'=>'França'),
  array('codigo'=>241, 'nome_pais'=>'Gabão'),
  array('codigo'=>220, 'nome_pais'=>'Gâmbia'),
  array('codigo'=>233, 'nome_pais'=>'Gana'),
  array('codigo'=>995, 'nome_pais'=>'Geórgia'),
  array('codigo'=>350, 'nome_pais'=>'Gibraltar'),
  array('codigo'=>1, 'nome_pais'=>'Granada'),
  array('codigo'=>30, 'nome_pais'=>'Grécia'),
  array('codigo'=>299, 'nome_pais'=>'Groenlândia'),
  array('codigo'=>590, 'nome_pais'=>'Guadalupe'),
  array('codigo'=>671, 'nome_pais'=>'Guam'),
  array('codigo'=>502, 'nome_pais'=>'Guatemala'),
  array('codigo'=>592, 'nome_pais'=>'Guiana'),
  array('codigo'=>594, 'nome_pais'=>'Guiana Francesa'),
  array('codigo'=>224, 'nome_pais'=>'Guiné'),
  array('codigo'=>245, 'nome_pais'=>'Guiné-Bissau'),
  array('codigo'=>240, 'nome_pais'=>'Guiné Equatorial'),
  array('codigo'=>509, 'nome_pais'=>'Haiti'),
  array('codigo'=>504, 'nome_pais'=>'Honduras'),
  array('codigo'=>852, 'nome_pais'=>'Hong Kong'),
  array('codigo'=>36, 'nome_pais'=>'Hungria'),
  array('codigo'=>967, 'nome_pais'=>'Iêmen'),
  array('codigo'=>1, 'nome_pais'=>'Ilhas Cayman'),
  array('codigo'=>672, 'nome_pais'=>'Ilha Christmas'),
  array('codigo'=>672, 'nome_pais'=>'Ilhas Cocos'),
  array('codigo'=>682, 'nome_pais'=>'Ilhas Cook'),
  array('codigo'=>298, 'nome_pais'=>'Ilhas Féroe'),
  array('codigo'=>672, 'nome_pais'=>'Ilha Heard e Ilhas McDonald'),
  array('codigo'=>960, 'nome_pais'=>'Maldivas'),
  array('codigo'=>500, 'nome_pais'=>'Ilhas Malvinas'),
  array('codigo'=>1, 'nome_pais'=>'Ilhas Marianas do Norte'),
  array('codigo'=>692, 'nome_pais'=>'Ilhas Marshall'),
  array('codigo'=>672, 'nome_pais'=>'Ilha Norfolk'),
  array('codigo'=>677, 'nome_pais'=>'Ilhas Salomão'),
  array('codigo'=>1, 'nome_pais'=>'Ilhas Virgens Americanas'),
  array('codigo'=>1, 'nome_pais'=>'Ilhas Virgens Britânicas'),
  array('codigo'=>91, 'nome_pais'=>'Índia'),
  array('codigo'=>62, 'nome_pais'=>'Indonésia'),
  array('codigo'=>98, 'nome_pais'=>'Irã'),
  array('codigo'=>964, 'nome_pais'=>'Iraque'),
  array('codigo'=>353, 'nome_pais'=>'Irlanda'),
  array('codigo'=>354, 'nome_pais'=>'Islândia'),
  array('codigo'=>972, 'nome_pais'=>'Israel'),
  array('codigo'=>39, 'nome_pais'=>'Itália'),
  array('codigo'=>1, 'nome_pais'=>'Jamaica'),
  array('codigo'=>81, 'nome_pais'=>'Japão'),
  array('codigo'=>962, 'nome_pais'=>'Jordânia'),
  array('codigo'=>686, 'nome_pais'=>'Kiribati'),
  array('codigo'=>383, 'nome_pais'=>'Kosovo'),
  array('codigo'=>965, 'nome_pais'=>'Kuwait'),
  array('codigo'=>856, 'nome_pais'=>'Laos'),
  array('codigo'=>266, 'nome_pais'=>'Lesoto'),
  array('codigo'=>371, 'nome_pais'=>'Letônia'),
  array('codigo'=>961, 'nome_pais'=>'Líbano'),
  array('codigo'=>231, 'nome_pais'=>'Libéria'),
  array('codigo'=>218, 'nome_pais'=>'Líbia'),
  array('codigo'=>423, 'nome_pais'=>'Liechtenstein'),
  array('codigo'=>370, 'nome_pais'=>'Lituânia'),
  array('codigo'=>352, 'nome_pais'=>'Luxemburgo'),
  array('codigo'=>853, 'nome_pais'=>'Macau'),
  array('codigo'=>389, 'nome_pais'=>'República da Macedônia'),
  array('codigo'=>261, 'nome_pais'=>'Madagascar'),
  array('codigo'=>60, 'nome_pais'=>'Mal'),
  array('codigo'=>265, 'nome_pais'=>'Malawi'),
  array('codigo'=>223, 'nome_pais'=>'Mali'),
  array('codigo'=>356, 'nome_pais'=>'Malta'),
  array('codigo'=>212, 'nome_pais'=>'Marrocos'),
  array('codigo'=>596, 'nome_pais'=>'Martinica'),
  array('codigo'=>230, 'nome_pais'=>'Maurícia'),
  array('codigo'=>222, 'nome_pais'=>'Mauritânia'),
  array('codigo'=>269, 'nome_pais'=>'Mayotte'),
  array('codigo'=>52, 'nome_pais'=>'México'),
  array('codigo'=>691, 'nome_pais'=>'Estados Federados da Micronésia'),
  array('codigo'=>258, 'nome_pais'=>'Moçambique'),
  array('codigo'=>373, 'nome_pais'=>'Moldávia'),
  array('codigo'=>377, 'nome_pais'=>'Mônaco'),
  array('codigo'=>976, 'nome_pais'=>'Mongólia'),
  array('codigo'=>382, 'nome_pais'=>'Montenegro'),
  array('codigo'=>1, 'nome_pais'=>'Montserrat'),
  array('codigo'=>95, 'nome_pais'=>'Myanmar'),
  array('codigo'=>264, 'nome_pais'=>'Namíbia'),
  array('codigo'=>674, 'nome_pais'=>'Nauru'),
  array('codigo'=>977, 'nome_pais'=>'Nepal'),
  array('codigo'=>505, 'nome_pais'=>'Nicarágua'),
  array('codigo'=>227, 'nome_pais'=>'Níger'),
  array('codigo'=>234, 'nome_pais'=>'Nigéria'),
  array('codigo'=>683, 'nome_pais'=>'Niue'),
  array('codigo'=>47, 'nome_pais'=>'Noruega'),
  array('codigo'=>687, 'nome_pais'=>'Nova Caledônia'),
  array('codigo'=>64, 'nome_pais'=>'Nova Zelândia'),
  array('codigo'=>968, 'nome_pais'=>'Omã'),
  array('codigo'=>31, 'nome_pais'=>'Países Baixos'),
  array('codigo'=>680, 'nome_pais'=>'Palau'),
  array('codigo'=>970, 'nome_pais'=>'Palestina'),
  array('codigo'=>507, 'nome_pais'=>'Panamá'),
  array('codigo'=>675, 'nome_pais'=>'Papua-Nova Guiné'),
  array('codigo'=>92, 'nome_pais'=>'Paquistão'),
  array('codigo'=>595, 'nome_pais'=>'Paraguai'),
  array('codigo'=>51, 'nome_pais'=>'Peru'),
  array('codigo'=>689, 'nome_pais'=>'Polinésia Francesa'),
  array('codigo'=>48, 'nome_pais'=>'Polônia'),
  array('codigo'=>1, 'nome_pais'=>'Porto Rico'),
  array('codigo'=>351, 'nome_pais'=>'Portugal'),
  array('codigo'=>974, 'nome_pais'=>'Qatar'),
  array('codigo'=>254, 'nome_pais'=>'Quênia'),
  array('codigo'=>996, 'nome_pais'=>'Quirguistão'),
  array('codigo'=>44, 'nome_pais'=>'Reino Unido'),
  array('codigo'=>236, 'nome_pais'=>'República Centro-Africana'),
  array('codigo'=>1, 'nome_pais'=>'República Dominicana'),
  array('codigo'=>420, 'nome_pais'=>'República Tcheca'),
  array('codigo'=>262, 'nome_pais'=>'Reunião'),
  array('codigo'=>40, 'nome_pais'=>'Romênia'),
  array('codigo'=>250, 'nome_pais'=>'Ruanda'),
  array('codigo'=>7, 'nome_pais'=>'Rússia'),
  array('codigo'=>212, 'nome_pais'=>'Saara Ocidental'),
  array('codigo'=>685, 'nome_pais'=>'Samoa'),
  array('codigo'=>1, 'nome_pais'=>'Samoa Americana'),
  array('codigo'=>290, 'nome_pais'=>'Santa Helena'),
  array('codigo'=>1, 'nome_pais'=>'Santa Lúcia'),
  array('codigo'=>1, 'nome_pais'=>'São Cristóvão e Nevis'),
  array('codigo'=>378, 'nome_pais'=>'São Marinho'),
  array('codigo'=>508, 'nome_pais'=>'Saint-Pierre e Miquelon'),
  array('codigo'=>239, 'nome_pais'=>'São Tomé e Príncipe'),
  array('codigo'=>1, 'nome_pais'=>'São Vicente e Granadinas'),
  array('codigo'=>248, 'nome_pais'=>'Seicheles'),
  array('codigo'=>221, 'nome_pais'=>'Senegal'),
  array('codigo'=>232, 'nome_pais'=>'Serra Leoa'),
  array('codigo'=>381, 'nome_pais'=>'Sérvia'),
  array('codigo'=>65, 'nome_pais'=>'Singapura'),
  array('codigo'=>963, 'nome_pais'=>'Síria'),
  array('codigo'=>252, 'nome_pais'=>'Somália'),
  array('codigo'=>94, 'nome_pais'=>'Sri Lanka'),
  array('codigo'=>268, 'nome_pais'=>'Suazilândia'),
  array('codigo'=>249, 'nome_pais'=>'Sudão'),
  array('codigo'=>211, 'nome_pais'=>'Sudão do Sul'),
  array('codigo'=>46, 'nome_pais'=>'Suécia'),
  array('codigo'=>41, 'nome_pais'=>'Suíça'),
  array('codigo'=>597, 'nome_pais'=>'Suriname'),
  array('codigo'=>992, 'nome_pais'=>'Tadjiquistão'),
  array('codigo'=>66, 'nome_pais'=>'Tailândia'),
  array('codigo'=>886, 'nome_pais'=>'República da China'),
  array('codigo'=>255, 'nome_pais'=>'Tanzânia'),
  array('codigo'=>246, 'nome_pais'=>'Território Britânico do Oceano Índico'),
  array('codigo'=>670, 'nome_pais'=>'Timor-Leste'),
  array('codigo'=>228, 'nome_pais'=>'Togo'),
  array('codigo'=>690, 'nome_pais'=>'Tokelau'),
  array('codigo'=>676, 'nome_pais'=>'Tonga'),
  array('codigo'=>1, 'nome_pais'=>'Trinidad e Tobago'),
  array('codigo'=>216, 'nome_pais'=>'Tunísia'),
  array('codigo'=>1, 'nome_pais'=>'Turcas e Caicos'),
  array('codigo'=>993, 'nome_pais'=>'Turquemenistão'),
  array('codigo'=>90, 'nome_pais'=>'Turquia'),
  array('codigo'=>688, 'nome_pais'=>'Tuvalu'),
  array('codigo'=>380, 'nome_pais'=>'Ucrânia'),
  array('codigo'=>256, 'nome_pais'=>'Uganda'),
  array('codigo'=>598, 'nome_pais'=>'Uruguai'),
  array('codigo'=>998, 'nome_pais'=>'Uzbequistão'),
  array('codigo'=>678, 'nome_pais'=>'Vanuatu'),
  array('codigo'=>379, 'nome_pais'=>'Vaticano'),
  array('codigo'=>58, 'nome_pais'=>'Venezuela'),
  array('codigo'=>84, 'nome_pais'=>'Vietnã'),
  array('codigo'=>681, 'nome_pais'=>'Wallis e Futuna'),
  array('codigo'=>260, 'nome_pais'=>'Zâmbia'),
  array('codigo'=>263, 'nome_pais'=>'Zimbábue')
);